services:
  springboot-app:
    image: ${DOCKERHUB_USERNAME}/findex-app:latest
    container_name: findex-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - OPENAPI_URI=${OPENAPI_URI}
      - OPENAPI_KEY=${OPENAPI_KEY}
    depends_on:
      - db
  db:
    image: postgres
    container_name: findex-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
