name: Findex

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        env:
          PROD_DB_URL: ${{ secrets.DB_URL }}
          PROD_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          PROD_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          OPENAPI_URI: ${{secrets.OPENAPI_URI}}
          OPENAPI_KEY: ${{secrets.OPENAPI_KEY}}
        run: ./gradlew bootJar -Dspring.profiles.active=prod

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service Findex --detach
